import type { Metadata } from "next";
import TaxonomySidebarServer from "@/components/custom/TaxonomySidebar/TaxonomySidebarServer";
import Link from "next/link";
import ArrowTopOfPage from "@/components/custom/ArrowTopOfPage";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PostLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="tool">
      <TaxonomySidebarServer />
      <main className="tool__container article-padding">
        <Link href="/tools" className="tool__back">
          ← Back to tools
        </Link>
        {children}
        <div className="tool__return-top">
          <ArrowTopOfPage />
        </div>
      </main>
    </div>
  );
}
