import type { Metadata } from "next";
import "../../globals.css";
import Aside from "@/components/custom/Aside";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PostLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen w-full">
      <Aside asideFor="tools" />
      <main className="flex min-h-screen justify-center article-padding mb-8">
        {children}
      </main>
    </div>
  );
}
