import type { Metadata } from "next";
import "../globals.css";
import Aside from "@/components/custom/Aside";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen w-full">
      <Aside />
      <main className="flex h-screen justify-end article-padding">
        {children}
      </main>
    </div>
  );
}

/*
Contenu -> padding left = 100vw - 1440/2 + taille sidebar

sidebar -> padding left = max 32px, calc ((100%-1440) -64) / 2
sidebar width ->
*/
